# Example 7
#
# Pulling out all the stops with cluster of seven Vagrant boxes.
#
domain   = 'example.com'
code_dir = '/opt/code'

nodes = [
  { :hostname => 'proxy',   :ip => '192.168.0.42', :box => 'precise32' },
  { :hostname => 'db',      :ip => '192.168.0.43', :box => 'precise32' },
  { :hostname => 'web1',    :ip => '192.168.0.44', :box => 'precise32' },
  { :hostname => 'web2',    :ip => '192.168.0.45', :box => 'precise32' },
  { :hostname => 'static1', :ip => '192.168.0.46', :box => 'precise32' },
  { :hostname => 'static2', :ip => '192.168.0.47', :box => 'precise32' },
  { :hostname => 'cache',   :ip => '192.168.0.48', :box => 'precise32' },
]

Vagrant::Config.run do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.host_name = node[:hostname] + '.' + domain
      node_config.vm.network :hostonly, node[:ip]
      node_config.vm.share_folder 'code', '/home/vagrant/code', code_dir

      memory = node[:ram] ? node[:ram] : 256;
      node_config.vm.customize [
        'modifyvm', :id,
        '--name', node[:hostname],
        '--memory', memory.to_s
      ]
    end
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
  end
end
