# Example 7
#
# Single box with AWS provider and sample static/dynamic sites via Puppet.
#
# NOTE: Make sure you install the Vagrant AWS plugin...
#   vagrant plugin install vagrant-aws
#
# Make sure you add the following dummy box...
#   vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
#
# Also add a new security group in the EC2 us-west-2 region called "vagrant"
# and open ports 22 and 80 to all inbound traffic.
#
# Use the following command to spin up the box...
#   vagrant up --provider=aws

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.ssh.username = "ubuntu"

  config.vm.provider :aws do |aws|
    aws.access_key_id = "YOUR_ACCESS_KEY_ID"
    aws.secret_access_key = "YOUR_SECRET_ACCESS_KEY"
    aws.keypair_name = "YOUR_KEYPAIR_NAME"
    aws.ssh_private_key_path = "PATH_TO_YOUR_PRIVATE_KEY"

    aws.ssh_username = "ubuntu"
    aws.region = "us-west-2"
    aws.ami = "ami-4ad94c7a"
    aws.instance_type = "t1.micro"
    aws.security_groups = [ "vagrant" ]

    aws.tags = {
      Name: "Vagrant AWS"
    }
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "puppet/modules"
  end
end
