# Example 1
#
# Create a Lucid 32-bit box with default configuration.
#
Vagrant::Config.run do |config|
  config.vm.box = 'lucid32'
  config.vm.box_url = 'http://files.vagrantup.com/lucid32.box'
end

