# Example 1
#
# Create a Precise 32-bit box with default configuration.
#
Vagrant::Config.run do |config|
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'
end

